[app_settings]
debug = true
app_port = 8000
app_version = "1.0.0"
app_name = "roomschool"
app_host = "0.0.0.0"
app_mount = "/api/v1"
app_key = 'my_key'
secret_key = "key"
cookie_name = "auth_session"
cookie_max_age_days = 7


[db_settings]
db_name = "roomschool_main_db"
db_user = "postgres"
db_password = "boss"
db_host = "localhost"
db_port = 5432

[clients_settings]
admin_url = 'http://admin.roomschool.ru'